// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2_EKFMbnLsOYxvpth9Vo0gjUPhTRsUM0',
    appId: '1:697534615822:web:844ef832f79a82f979c75f',
    messagingSenderId: '697534615822',
    projectId: 'viatlis-appointments',
    authDomain: 'viatlis-appointments.firebaseapp.com',
    storageBucket: 'viatlis-appointments.firebasestorage.app',
    measurementId: 'G-TL1Y3MZLCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAuNKRhg2TijDoTUJRqn50Tjy_0izktSs',
    appId: '1:697534615822:android:31a45d6983e1bc5479c75f',
    messagingSenderId: '697534615822',
    projectId: 'viatlis-appointments',
    storageBucket: 'viatlis-appointments.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcjQFcXBDEjgGIRWjHlAanfV55XVnqKNk',
    appId: '1:697534615822:ios:a4c64a53dc5f794479c75f',
    messagingSenderId: '697534615822',
    projectId: 'viatlis-appointments',
    storageBucket: 'viatlis-appointments.firebasestorage.app',
    iosBundleId: 'Riphahmalakand.example.vitalisAppointments',
  );
}
